# This is a basic workflow to help you get started with Actions
name: actions-building-deploying-angular-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1 # this installs node and npm
        with:
          node-version: '12.x'
      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Clean Cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
      - name: Install angular
        run: npm install -g @angular/cli > /dev/null
      - name: Build
        run: ng build
      - name: Archive build
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
