name: actions-building-deploying-angular-app

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules # this allows for re-using node_modules caching, making builds a bit faster.
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm cache clean --force
          npm install
          npm install -g @angular/cli > /dev/null
      - name: Build
        run: ng build
      - name: Archive build
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          source: "/dist/user-application/"
          target: ${{ secrets.PATH }}
          strip_components: 2
